INSERT INTO `nxx_user_role` (`ROLE_ID`, `ROLE_DESCRIPTION`, `STATUS`, `CREATE_USER`, `CREATE_DATE`, `UPDATE_USER`, `UPDATE_DATE`) VALUES (NULL, 'Guest', 'A', 'IT00', '2020-07-24', '', '');

INSERT INTO `nxx_role_access` (`ACCESS_ID`, `ROLE_ID`, `MODULE_ACCESS`, `STATUS`, `CREATE_USER`, `CREATE_DATE`, `UPDATE_USER`, `UPDATE_DATE`) VALUES (NULL, '7', '4', 'A', 'IT00', '2020-07-24', '', '');