DROP VIEW IF EXISTS `v_participants`;

CREATE VIEW v_participants AS                                
SELECT A.ACTIVITY_ID,
GROUP_CONCAT(CONCAT(B.EMP_FNAME,' ',B.EMP_LNAME) SEPARATOR ', ') AS `PARTICIPANTS`,
GROUP_CONCAT(A.EMP_CODE SEPARATOR ', ') AS `PARTICIPANT_ID`,A.STATUS
FROM nets_emp_act_participants AS A
	LEFT JOIN nets_emp_info AS B
		ON A.EMP_CODE = B.EMP_CODE
	WHERE A.STATUS IN ('DONE','CONFIRMED')
	GROUP BY A.ACTIVITY_ID