ALTER TABLE `nets_emp_info` 
CHANGE `POS_CODE` `POS_CODE` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
CHANGE `LOC_CODE` `LOC_CODE` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
CHANGE `GRP_CODE` `GRP_CODE` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
CHANGE `DEPT_CODE` `DEPT_CODE` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
CHANGE `PRESENT_ADDR1` `PRESENT_ADDR1` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `PRESENT_ADDR2` `PRESENT_ADDR2` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `MOBILE_NO` `MOBILE_NO` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
CHANGE `TEL_NO` `TEL_NO` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `TEAM` `TEAM` VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;